name: Caching

on:
  workflow_dispatch:
    inputs:
      name:
        description: "What needs updating?"

jobs:
  build:
    permissions:
      actions: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      with:
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt